config/routes.rb
Rails.application.routes.draw do
  root to: 'jobs#index'
  resources :companies, only:[:show,:new,:create]
  resources :jobs, only:[:show,:new,:create,:edit,:update]
  resources :categories, only:[:show,:new,:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
 belongs_to :company
 belongs_to :category

 validates :title,:location,:description,:category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @jobs = Job.all
    @companies = Company.all
  end
  def new
    @category = Category.new
    @jobs = Job.all
    @companies = Company.all
  end
  def create
    @jobs = Job.all
    categories_params = params.require(:category).permit(:name)
    @category = Category.new
    @category.save
    redirect_to @category
  end
  def show
    @jobs = Job.all
    @category = Category.find(params[:id])
  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
    @jobs = Job.all
  end
  def new
    @company = Company.new
  end
  def create
    @company = Company.new
    @company.name = params[:company][:name]
    @company.location = params[:company][:location]
    @company.mail = params[:company][:mail]
    @company.phone = params[:company][:phone]
    @company.save
    redirect_to @company
  end
  def show
    @company = Company.find(params[:id])
    @jobs = Job.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
    @companies = Company.all
    @categories = Category.all
  end
  def show
    @job = Job.find(params[:id])
  end
  def new
    @job = Job.new
    @companies =  Company.all
    @categories = Category.all
  end
  def create
    @categories = Category.all
    @companies =  Company.all
    @job = Job.new(job_params)
    if  @job.save
    redirect_to @job
    else
      flash[:error] = "Não foi possível criar a vaga"
      render :new
    end
  end
  def edit
    @job = Job.find(params[:id])
    @companies = Company.all
    @categories = Category.all
  end
  def update
    @categories = Category.all
    @companies = Company.all
    @job = Job.find(params[:id])
    if @job.update(job_params)
    redirect_to @job
    else
    flash[:error] = 'Não foi possível atualizar a vaga'
    render :edit
    end
  end

private

  def job_params
  params.require(:job).permit(:title,:location,:category_id,:company_id,:description,:featured)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<% @category.jobs.each do |job| %>
  <h1> <%= @category.name %> </h1>
  <%= job.title %>
  <%= job.location %>
  <% end %>

  Nenhuma vaga disponível

app/views/companies/new.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>

  <%= f.label :location, 'Local' %>
  <%= f.text_field :location %>

  <%= f.label :mail, 'Email' %>
  <%= f.text_field :mail %>

  <%= f.label :phone, 'Telefone' %>
  <%= f.text_field :phone %>

  <%= f.submit  'Criar Empresa'%>

  <% end %>

app/views/companies/show.html.erb
<h1> <%= @company.name %> </h1>
<%= @company.location %>
<%= @company.mail %>
<%= @company.phone %>

<h2>VAGAS</H2>

<% @company.jobs.each do |job| %>
  <%= job.title %>
  <%= job.category.name %>
<% end %>

<% if @company.jobs.empty? %>
  Nenhuma vaga disponível
<% end %>

app/views/jobs/edit.html.erb
<%= flash[:error] %>
<%= form_for @job do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>

  <%= f.label :location, 'Local' %>
  <%= f.text_field :location %>

  <%= f.label :category, 'Categoria' %>
  <%= f.text_field :category %>

  <%= f.label :company_id, 'Empresa' %>
  <%= f.collection_select :company_id, @companies, :id, :name %>

  <%= f.label :description, 'Descrição' %>
  <%= f.text_field :description %>

  <%= f.label :featured, 'Destaque' %>
  <%= f.check_box :featured %>

  <%= f.submit 'Atualizar Vaga' %>
<% end %>

app/views/jobs/index.html.erb
Emprego Já
<% @jobs.each do |job| %>
  <h1>  <%= link_to job.title, job_path(job) %> </h1>
  : <%= job.location %>
  : <%= job.company.name %>

  <% if job.featured == true %>
     <strong>Destaque</strong>
  <% end %>
<%end%>
<br>

<%= link_to 'Nova Compania', new_company_path %>

<br>

<% @companies.each do |company| %>
  <%= link_to company.name , company_path(company) %>
<% end %>

<% @categories.each do |category| %>
  <%= link_to category.name , category_path(category) %>
<% end %>

app/views/jobs/new.html.erb
<h2> <%= flash[:error] %> </h2>
<%= form_for @job do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>

  <%= f.label :location, 'Local' %>
  <%= f.text_field :location %>

  <%= f.label :category_id, 'Categoria' %>
  <%= f.collection_select :category_id, @categories, :id, :name  %>

  <%= f.label :company_id, 'Empresa' %>
  <%= f.collection_select :company_id, @companies, :id, :name %>

  <%= f.label :description, 'Descrição' %>
  <%= f.text_field :description %>

  <%= f.label :featured, 'Destaque' %>
  <%= f.check_box :featured %>

  <%= f.submit 'Criar Vaga' %>
<% end %>

app/views/jobs/show.html.erb
<h1>  <%= @job.title %> </h1>
<%= @job.category.name %>
<%= @job.company.name %>
<%= @job.description %>
<%= @job.location %>

<% if @job.featured == true %>
  <strong>Destaque</strong>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmpregoJa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>